image: ubuntu

stages:
    - build
    - deploy

build_job:
    stage: build
    before_script:
        - apt-get update
        - apt-get install -y nginx
        - apt-get install -y zip
    script:
        - git clone https://gitlab.com/shashank3656/basic_php.git
        - cd basic_php
        - cd ..
        - zip -r basic_php.zip basic_php

    artifacts:
        paths:
            - basic_php.zip
    tags:
        - docker

    only:
        - main    

deploy-dev-job:      
    stage: deploy
    variables:
        SERVER: "$DEV_SERVER"
    tags:
        - myrunner
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
        - mkdir -p ~/.ssh
        - eval `ssh-agent -s`
        - echo "$PRIVATE_SSH_KEY" | tr -d '\r' | ssh-add -
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh-keyscan -t rsa $DEV_SERVER >> ~/.ssh/known_hosts
    script:
        - ssh ubuntu@$SERVER "cd /home/ubuntu && ls"
    tags:
        - myrunner
    only:
        - main                   
